services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app/app
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    # volumes:
    #   - .:/usr/src/app
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
